### ISSUE TITLE
Error while trying to compile Minios

### ISSUE THREAD

**Issue by p4pe** [sysml/clickos#47]
I have been trying to compile clickos with minios on a virtualized Xen machine but I've run into a weird issue and I've been wondering if you could aid me.  I am attaching a screenshot of the error. While I am following the guide on the website when it comes to building clickos I get an error message.

![VirtualBox_UbuntuServer_15_09_2020_17_39_06](https://user-images.githubusercontent.com/35313995/93310441-733f1a00-f80d-11ea-8521-c7ebd3d80581.png)

**Comment by WillFantom** [comment]
If you are using the most recent `sysml/mini-os`, perhaps a simple change to `minios/config.mk.in` like [this](https://github.com/WillFantom/ClickOS/commit/d8d28f99117728ca9da3f2568bf5986feadfe2e9) might help 👍

**Comment by p4pe** [comment]
Thank you for your answer, I will try it and i give an update

**Comment by p4pe** [comment]
The same error again @WillFantom

**Comment by WillFantom** [comment]
You might have to use an older `g++` version (5.3 perhaps: xenial's default)

**Comment by p4pe** [comment]
Hi @WillFantom i tried with 4.8 version and with 5.5 (i did not find 5.3) 
And I had this error

<img width="449" alt="minios" src="https://user-images.githubusercontent.com/35313995/93458316-d18cfb00-f8e8-11ea-8c8a-0931fd5be9e9.png">

**Comment by WillFantom** [comment]
> If you are using the most recent `sysml/mini-os`, perhaps a simple change to `minios/config.mk.in` like [this](https://github.com/WillFantom/ClickOS/commit/d8d28f99117728ca9da3f2568bf5986feadfe2e9) might help 👍

Have you kept this change too? (and reconfigured) By the looks of it, this should fix it now

**Comment by p4pe** [comment]
Yes i kept the change in the `minios/config.mk.in`. After I run the `./configure --enable-minios --with-xen=$XEN_ROOT --with-minios=$MINIOS_ROOT
`

And I took the error.

**Comment by p4pe** [comment]
@WillFantom any thought, about what may went wrong?

**Comment by WillFantom** [comment]
After seeing your most recent screenshot, I do believe that the fix I sent at the start, in conjunction with the change in g++ version should be a valid fix. If that isn't working, I can suggest cloning the repo fresh and applying the fix, then running the configure and make steps. Otherwise, I suggest using a dockerized build environment: see [here](https://github.com/WillFantom/ClickOS-Docker).

**Comment by p4pe** [comment]
Thank you for your help @WillFantom 
Here is all the steps that i did:
I am installing Ubuntu 16.04, installing gcc-4.9 (or 5.5 in other attempts) and the respective g++ (same versions) and freezing them with apt-mark hold. I go on to install the rest of the dependencies (either one by one from the blog post or by running your script ClickOS-install).
Inevitably while the compilation of Xen works in all cases, when I reach the stage where it must compile (the "make minios" part) it fails showing the error message in the screenshots. I have tried going to /root/clickos/minios/config.mk.in and adding the CONFIG_BLKFRONT_PERSISTENT_GRANTS = y option in the end of the file. While running "./configure --enable-minios --with-xen=$XEN_ROOT --with-minios=$MINIOS_ROOT" does work (and changes the plain config.mk under the same directory) the compilation fails when I try to run "make minios" again.

**Comment by p4pe** [comment]
Probably its a silly question but, just to ensure it

![gra](https://user-images.githubusercontent.com/35313995/93991510-11def400-fd95-11ea-95c9-55d57ad1c5f6.png)

Does the empty line above "Persistent Grants" needed?

**Comment by IoakeimFotoglou** [comment]
It works with GCC/G++ 5.4, you just need to make the configuration change **before** running the ./configure (options). If you have done so then just remove the "_mini-os_" directory (the one referred to by the $MINIOS_ROOT variable), make the configuration change, clone the mini-os directory again and run the configuration again.
